# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name_plural': 'Canais',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('login', models.CharField(max_length=15, unique=True)),
                ('nome', models.CharField(max_length=60)),
                ('is_ativo', models.BooleanField(default=True, verbose_name='situação')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais', to='cad.Canal')),
            ],
            options={
                'ordering': ['login'],
            },
        ),
        migrations.CreateModel(
            name='MacroCanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name_plural': 'Macro Canais',
                'verbose_name': 'Macro Canal',
            },
        ),
        migrations.CreateModel(
            name='RegionalCanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name_plural': 'Regionais',
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regionais', to='cad.RegionalCanal'),
        ),
        migrations.AddField(
            model_name='canal',
            name='macro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macros', to='cad.MacroCanal'),
        ),
    ]
