# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0002_auto_20170721_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canais', to='cad.Canal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regionais', to='cad.RegionalCanal'),
        ),
    ]
